version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ADMINUSERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ADMINPASSWORD
      
    ports:
      - 27017:27017
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
  

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_SERVER=$MONGODB_SERVER
      - ME_CONFIG_MONGODB_PORT=$MONGODB_PORT
      - ME_CONFIG_MONGODB_DATABASE=$MONGODB_DATABASE    
      
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always


